[package]
name = "engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.*", features = ["backtrace"] }
anymap = "0.12.*"
winit = "0.27.5"
nalgebra = "0.32.2"
raw-window-handle = "0.5.2"
thiserror = "1.0"
log = "0.4.17"
once_cell = "1.17.1"
memoffset = "0.8"
image = "0.24.6"
indexmap = "1.9.3"
bytemuck = "1.13.1"
strum = { version = "0.25.0", features = ["derive", "strum_macros"] }
strum_macros = "0.25.1"
env_logger = "0.10.0"
bitflags = "2.2.*"
bevy_ecs = "0.12.*"
crossbeam = "0.8.*"
thunderdome = "0.6.*"
imgui = { version = "0.11.0", features = ["docking"] }
imgui-rs-vulkan-renderer = "1.9.0"
imgui-winit-support = "0.11.0"

rapier2d = { version = "0.17", features = ["simd-stable", "serde-serialize"] }

gpu = { path = "../gpu" }
engine_macros = { path = "../engine_macros" }
