name: test suite
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.18.x'
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features 
  miri:
    name: cargo miri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.18.x'
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "nightly"
          components: miri
      - run: cargo miri test --all-features
